[package]
name = "zv-core"
version.workspace = true
edition.workspace = true

[dependencies]
theymx = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
log.workspace = true
thiserror.workspace = true

lazy_static = "1.5.0"
uuid = { workspace = true, features = ["serde"] }
