[package]
name = "zv-server"
version.workspace = true
edition.workspace = true

[dependencies]
zv-core.workspace = true

log.workspace = true
theymx.workspace = true
thiserror.workspace = true
serde.workspace = true
uuid.workspace = true

spin_sleep = "1.3.3"
crossbeam-channel = "0.5.15"
libftd2xx = "0.33.1"

[dev-dependencies]
pretty_env_logger = "0.5.0"
